"""add_color_field_to_animals

Revision ID: 24f846716da3
Revises: 46c1eaf9c935
Create Date: 2025-10-29 17:59:00.936325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24f846716da3'
down_revision = '46c1eaf9c935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('color', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'color')
    # ### end Alembic commands ###
