"""Initial migration

Revision ID: 54b26531e228
Revises: 
Create Date: 2025-10-22 14:10:17.394602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b26531e228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelters',
    sa.Column('shelter_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('primary_account_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['primary_account_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('shelter_id')
    )
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelters_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('GENERAL_MEMBER', 'SHELTER_MEMBER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('primary_shelter_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=1024), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=6), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=6), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['primary_shelter_id'], ['shelters.shelter_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('animals',
    sa.Column('animal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('species', sa.Enum('CAT', 'DOG', name='species'), nullable=True),
    sa.Column('breed', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'UNKNOWN', name='sex'), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PUBLISHED', 'RETIRED', name='animalstatus'), nullable=False),
    sa.Column('shelter_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('medical_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.shelter_id'], ),
    sa.PrimaryKeyConstraint('animal_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('owner_type', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('audit_logs',
    sa.Column('audit_log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('target_type', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('shelter_id', sa.BigInteger(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.shelter_id'], ),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=6), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=6), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('animal_images',
    sa.Column('animal_image_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.animal_id'], ),
    sa.PrimaryKeyConstraint('animal_image_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.BigInteger(), nullable=False),
    sa.Column('animal_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('ADOPTION', 'REHOME', name='applicationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=6), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=6), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.animal_id'], ),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_idempotency_key'), ['idempotency_key'], unique=True)

    op.create_table('medical_records',
    sa.Column('medical_record_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.BigInteger(), nullable=False),
    sa.Column('record_type', sa.Enum('TREATMENT', 'CHECKUP', 'VACCINE', 'SURGERY', 'OTHER', name='recordtype'), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=6), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=6), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.animal_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('medical_record_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_idempotency_key'))

    op.drop_table('applications')
    op.drop_table('animal_images')
    op.drop_table('notifications')
    op.drop_table('jobs')
    op.drop_table('audit_logs')
    op.drop_table('attachments')
    op.drop_table('animals')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelters_slug'))

    op.drop_table('shelters')
    # ### end Alembic commands ###
